# Generated by Django 4.0.4 on 2022-04-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50)),
                ('smerovaci_cislo', models.IntegerField()),
                ('ulice', models.CharField(max_length=50)),
                ('cislo_popisne', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('kapacita', models.IntegerField()),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volejbal.adresa')),
            ],
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('hala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volejbal.hala')),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=40)),
                ('datum_narozeni', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolo', models.IntegerField()),
                ('domaci_sety', models.IntegerField()),
                ('hoste_sety', models.IntegerField()),
                ('datum_zapasu', models.DateTimeField()),
                ('domaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci', to='volejbal.klub')),
                ('hoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoste', to='volejbal.klub')),
            ],
        ),
        migrations.CreateModel(
            name='Tabulka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapasy_celkem', models.IntegerField()),
                ('vyhry', models.IntegerField()),
                ('prohry', models.IntegerField()),
                ('vyhrane_sety', models.IntegerField()),
                ('prohrane_sety', models.IntegerField()),
                ('body', models.IntegerField()),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volejbal.klub')),
            ],
        ),
        migrations.AddField(
            model_name='klub',
            name='trener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volejbal.trener'),
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=40)),
                ('datum_narozeni', models.DateTimeField()),
                ('pozice', models.CharField(max_length=50)),
                ('vyska', models.IntegerField()),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volejbal.klub')),
            ],
        ),
    ]
